### PR TITLE
Release/v2

### PR DESCRIPTION
**Pull request by iamstarkov**

### CODE REVIEW

**Comment by iamstarkov** [comment]
will fix #340

**Comment by iamstarkov** [comment]
published as `2.0.0-rc.1` or `@next`:

```
yarn add nordnet-ui-kit@2.0.0-rc.1
# or
yarn add nordnet-ui-kit@next
```

@codler, @JCB-K i want you to try it and explicitly report here problems or lack of it

**Comment by JCB-K** [comment]
I'm still getting the following error with nordnet-ui-kit@2.0.0-rc-1 and react-jss@8.3.3.

> Warning: Failed context type: Invalid context `64a55d578f856d258dc345b094a2a2b3` of type `Jss` supplied to `Jss(Button)`, expected instance of `Jss`.
    in Jss(Button) (at index.js:7)

**Comment by codler** [comment]
@mlenser Can you try this version with the tables thing?

**Comment by mlenser** [comment]
Yup, planning on it. It should work without issue since we added the example, but I'll test it.

**Comment by JCB-K** [comment]
works for Shareville now 🎈

**Comment by iamstarkov** [comment]
works for webapp-next

**Pull request merged**
