### PR TITLE
Feature/jss 8 migration

### PR DESCRIPTION
**Pull request by iamstarkov**
we need to utilise jss@8, to migrate to react-jss iteratively.
but jss-theme-reactor is abandoned, so me and @RikardGehlin rewrote it https://github.com/nathanmarks/jss-theme-reactor/pull/46 and republished it https://www.npmjs.com/package/@iamstarkov/jss-theme-reactor

in the app we would need to use webpack's `resolve.alias`es while all modules are being rewritten to react-jss

### CODE REVIEW

**Comment by iamstarkov** [comment]
i guess we need .npmrc file in here

**Comment by iamstarkov** [comment]
@bstream but apart from lock file issues, what do you think of this?

**Comment by iamstarkov** [comment]
@bstream fixed registry issue

**Comment by robineng** [comment]
Hot stuff

**Comment by iamstarkov** [comment]
Published as `1.6.0`

**Comment by iamstarkov** [comment]
I also added some compatibility notes in the readme

**Pull request merged**
