### PR TITLE
fix(jss-theme-reactor): bump jss-theme-reactor to get rid off prop-types warnings

### PR DESCRIPTION
**Pull request by iamstarkov**
title says it all

### CODE REVIEW

**Comment by iamstarkov** [comment]
this diff is essentially the only change from 0.12.1 and 0.12.5:

```diff
// package.json
-    "react": "^15.3.2",
+    "prop-types": "^15.5.0",
+    "react": "^15.5.0",

// src/ThemeProvider.js
-import { Component, PropTypes } from 'react';
+import { Component } from 'react';
+import PropTypes from 'prop-types';
```

**Comment by DavidTatti** [comment]
Awesome!:)

**Comment by iamstarkov** [comment]
released as v1.18.1

**Pull request merged**
