### PR TITLE
Lock all versions in package.json to avoid errors with clashing versions

### PR DESCRIPTION
**Pull request by bstream**
Lock versions to prevent future errors.

What do you guys say? @JohnPhoto @dimchez @GU5TAF

### CODE REVIEW

**Comment by iamstarkov** [comment]
`shrinkwrap` is more suitable for this goal

**Comment by dimchez** [comment]
@iamstarkov I agree regarding `shrinkwrap`. Still specifying exact version number is better than it was.

**Comment by iamstarkov** [comment]
npm will pay no attention to `package.json` if you will have `npm-shrinkwrap.json` in the repo

**Comment by GU5TAF** [comment]
Closing this, feel free to submit a new PR with shrinkwrap if you want 😉

**Pull request closed without merging**
