### PR TITLE
feat: add a solid triangle

### PR DESCRIPTION
**Pull request by mjmonline**

### CODE REVIEW

**Comment by mjmonline** [comment]
This to replace CSS triangles

**Comment by mjmonline** [comment]
@JacobBlomgren good catch, fix pushed

**Comment by JacobBlomgren** [comment]
@mjmonline are you sure I can't see a commit and it's not updated here https://nordnet-ui-kit-px5q5gcmh.now.sh/#icon

**Comment by mjmonline** [comment]
@JacobBlomgren ahh the push failed. Check now please

**Comment by JacobBlomgren** [comment]
@mjmonline cool. And now I wonder another thing, sorry for the inconvenience, but if you look at `SolidArrowUp`, doesn't it look awfully similar?

**Comment by mjmonline** [comment]
@JacobBlomgren it does, but it's not a 90degree angle on the corner pointing up. Thats what design wants :)

**Comment by JacobBlomgren** [comment]
@mjmonline go ahead then

**Pull request merged**
