### PR TITLE
[WIP] JSS and theme in ui-kit

### PR DESCRIPTION
**Pull request by bstream**

### CODE REVIEW

**Comment by bstream** [comment]
This will land on `next` branch (not `master`)

**Comment by bstream** [comment]
Here is the documentation generated by this PR: https://bstream.github.io/nordnet-ui-kit/

**Comment by JohnPhoto** [comment]
Maybe we should add a milestone-thingie with issues for each component to port?

**Comment by bstream** [comment]
We should! 👍

**Pull request merged**
